services:
  - type: web
    name: fleetops
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: OPENAI_API_KEY
        value: placeholder_key_set_in_dashboard
      - key: SERP_API_KEY
        value: placeholder_key_set_in_dashboard
      - key: TOKENIZERS_PARALLELISM
        value: false
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PIP_NO_CACHE_DIR
        value: 1
      - key: PORT
        value: 10000
    healthCheckPath: /
    plan: starter
    region: oregon
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: fleetops-disk
      mountPath: /opt/render/project/src/app/index_storage
      sizeGB: 1
